version: "3.9"
services:
  db:
    image: mysql:8.0
    container_name: schools-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: schools
      MYSQL_USER: schooluser
      MYSQL_PASSWORD: schoolpass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
